<!DOCTYPE html>
<html>
<style>

ul { list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;}

li { float: left;}

li a, .dropbtn
 {display: inline-block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;}

  li a:hover, .dropdown:hover .dropbtn 
  { background-color: red;}

li.dropdown {display: inline-block;}

.dropdown-content
 {display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;}

  .dropdown-content a 
  {color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;}

.dropdown-content a:hover {background-color: #f1f1f1;}

.dropdown:hover .dropdown-content {display: block;}

</style>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>project four</title>
</head>
<body>        
        <ul>
            <li><a href="#home">Clients Online Workshop</a></li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">User Options</a>
                  <div class="dropdown-content">
                    <a href="<?php echo Helper::createLink('user', ['view' => 'signup']);?>">Signup</a>
                    <a href="<?php echo Helper::createLink('user', ['view' => 'login']);?>">Register</a>
                  </div>
            </li>
        </ul>
    <div>
        <?php
        require $template;
        ?>
    </div>

</body>
</html>

