<?php

    function error_field($title, array $errors) 
    {
        foreach ($errors as $error) 
        {
            /* @var $error ValidatorError */
            if ($error->getSource() == $title) 
            { return ' style="background-color:pink;"'; }
        }
        return '';
    }
?>
    <div class="col-md-8 offset-lg-0">
        <h1 class="text-center">Welcome Client</h1>
        <hr>
    
    <div class="col-10 col-md-6 offset-1 offset-md-3">
<?php if (!empty($errors)): ?>
    <ul class="errors">
        <?php foreach ($errors as $error): ?>
            <?php /* @var $error ValidationError */ ?>
            <li><?php echo Helper::escape($error->getMessage()) ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
        <form target="_self" method="post">
            <?php
                if($action ==='signup'):
            ?>
                <div class="form-group">
                    <input type="text" placeholder="Name"  name="user[name]" 
                       class="form-control"<?php echo error_field('name', $errors); ?>/></div>
            <?php
                endif;
            ?>

            <?php
                if($action ==='signup'):
            ?>
                <div class="form-group">
                    <input type="text" placeholder="Surname"  name="user[surname]" 
                       class="form-control"<?php echo error_field('surname', $errors); ?>/></div>
            <?php
                endif;
            ?>

            <?php
                if($action ==='signup'):
            ?>
                <div class="form-group">
                    <input type="text" placeholder="Email address"  name="user[email]" 
                       class="form-control"<?php echo error_field('email', $errors); ?>/></div>
            <?php
                endif;
            ?>

            <?php
                if($action ==='signup'):
            ?>
                <div class="form-group">
                    <input type="password" name="user[password]" placeholder="Password" 
                      class="form-control"<?php echo error_field('password', $errors); ?>/>
            <?php
                endif;
            ?>

            <?php
                if($action ==='signup'):
            ?>
                <input type="password" name="user[passwordRepeat]" placeholder="Repeat Password" 
                    class="form-control" <?php echo error_field('passwordRepeat', $errors); ?>
                        style="margin-top:10px;"/>
            <?php
                endif;
            ?>
            </div>
            <div class="form-group">
                <button class="btn btn-danger float-right" type="submit" style="margin-right:20px;" 
                    name="cancel" value="cancel">Cancel</button>
                <button type="submit" style="margin-left:20px;"
                    <?php
                        if($action ==='signup' || $action ==='login'):
                    ?>
                        class="btn btn-success" 
                    <?php
                        endif;
                    ?>
                    name="<?php echo $action ?>" 
                    value="<?php echo $action ?>">
                    <?php echo ucfirst($action) ?> 
                </button>
            </div>
        </form>
    </div>
<style>
.errors {
    margin-bottom: 20px;
}
.errors li {
    color: red;
}
</style>
</div>