myName = input("What is your name?: ")
mySurname = input("What is your surname?: ")
myAge = input("How old are you?: ")
print("No offense but that's really OLD!")
print()
print("So you are ")
print(myName)
print(mySurname)
print("And you are ")
print(myAge)
print("years old")