myName = input("What is your name?: ")
mySurname = input("What is your surname?: ")
myAge = input("How old are you?: ")
print("No offense but that's really OLD!")
print()
print("So you are ",myName," ",mySurname," and you are ",myAge,"years old")
print("nice to meet you ",myName)
