<!DOCTYPE html>
<html>
    <head>
        <title>Insert Data</title>
</head>
<body>
    <form action = "process_form" method = "POST" >

    <label for = "name">Name: </label>
    <input type = "text" name = "name" id = "name" required>

    <label for = "position">Work position: </label>
    <input type = "text" name = "position" id = "position" required>

    <input type = "submit" value = "Submit">
</form>

<?php 
session_start();
if (isset($_SESSION['inserted_data']))
{
    //display the inserted data from the session
    echo "<h2>Inserted Data: </h2>";
    echo "<p><strong>Name: </strong>{$_SESSION['inserted_data']['name']}";
    echo "<p><strong>Work Position: </strong>{$_SESSION['inserted_data']['position']}";

    //clear the session data
    unset($_SESSION['inserted_data']);
}
?>

function __construct(){}

public function setParam(stdClass $client){

    if(array_key_exists('name', $client)){
        $this->name = $client->name;
    }

    if(array_key_exists('surname',$client)){
        $this->surname = $client->surname;
    }

    if(array_key_exists('email', $client)){
        $this->email = $client->email;
    }

    if(array_key_exist('cellno', $client)){
        $this->cellno = $client->institution;
    }
}