<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action="client.php" method="POST">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="surname">Surname:</label>
        <input type="text" id="surname" name="surname" required><br>

        <label for="email">Email:</label> 
       <input type="text" id="email" name="email" required><br>

       <label for="cellno">Cellphone:</label> 
       <input type="text" id="cellno" name="cellno" required><br>

        <input type="submit" value="Submit";>  
    </form>
<?php
session_start();
if (isset($_SESSION['inserted_data']))
{
    //display the inserted data from the session
    echo "<h2>Inserted Data: </h2>";
    echo "<p><strong>Name: </strong>{$_SESSION['inserted_data']['name']}";
    echo "<p><strong>Surname: </strong>{$_SESSION['inserted_data']['surname']}";
    echo "<p><strong>Email Address: </strong>{$_SESSION['inserted_data']['email']}";
    echo "<p><strong>Cellphone: </strong>{$_SESSION['inserted_data']['cellno']}";

    //clear the session data
    unset($_SESSION['inserted_data']);
}
?>
</body>
</html>





