<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action="view" method="POST">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="surname">Surname:</label>
        <input type="text" id="surname" name="surname" required><br>

        <label for="email">Email:</label> 
       <input type="text" id="email" name="email" required><br>

       <label for="cellno">Cellphone:</label> 
       <input type="text" id="cellno" name="cellno" required><br>

        <input type="submit" value="Submit";>  
    </form>

    </body>
</html>








