<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action = "view" method="POST">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="surname">Surname:</label>
        <input type="text" id="surname" name="surname" required><br>

        <label for="email">Email:</label> 
       <input type="text" id="email" name="email" required><br>

       <label for="cellno">Cellphone:</label> 
       <input type="text" id="cellno" name="cellno" required><br>

        <input type="submit" value="Submit" action="client";>  
 
    </form>
    </body>
</html>

<?php
$user = new Client;
$user->get_name('$user_name');
$user->get_surname('$user_surname');
$user->get_email('$user_email');
$user->get_cellno('$user_cellno');

if($_SERVER['REQUEST_METHOD'] === 'POST')
{ 
    $user_name =$_POST["name"];
    $user_surname =$_POST["surname"];
    $user_email =$_POST["email"];
    $user_cellno =$_POST["cellno"];

    echo"Name: ".$user_name;
    echo"<br>";
    echo"Surname: ".$user_surname;
    echo"<br>";
    echo"Email: ".$user_email;
    echo"<br>";
    echo"Cellphone: ".$user_cellno;
    echo"<br>";

}
?>








