<!DOCTYPE html>
<html>
<style>

/* Bordered form */
form {border: 3px solid #f1f1f1;}

/* Full-width inputs */
input[type=text], input[type=password] 
{ width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;}

/*style for all buttons */
button 
{background-color: #DC143C;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;}

/* hover effect for buttons */
button:hover {opacity: 0.8;}

/*style for the cancel button (black) */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #000000;
}

/* to center the avatar image inside this container */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

/* Avatar image */
img.avatar {
  width: 40%;
  border-radius: 50%;
}

/* Add padding to containers */
.container {
  padding: 16px;
}

/* The "Forgot password" text */
span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
    display: block;
    float: none;
  }
  .cancelbtn {
    width: 100%;
  }
}
</style>



<form target="_self" method="post">
<?php
    if($action ==='signup'):
?>
    <div class="form-group">
    <input type="text" placeholder="Name"  name="user[name]" 
    class="form-control"<?php echo error_field('name', $errors); ?>/></div>
    
    <div class="form-group">
    <input type="text" placeholder="Surname"  name="user[surname]" 
    class="form-control"<?php echo error_field('surname', $errors); ?>/></div>

    <div class="form-group">
    <input type="text" placeholder="Email address"  name="user[email]" 
    class="form-control"<?php echo error_field('email', $errors); ?>/></div>
    
    <div class="form-group">
    <input type="password" name="user[password]" placeholder="Password" 
    class="form-control"<?php echo error_field('password', $errors);?>/>
    
    <input type="password" name="user[passwordRepeat]" placeholder="Repeat Password" 
    class="form-control" <?php echo error_field('passwordRepeat', $errors); ?>
    style="margin-top:10px;"/></div>
<?php
    endif;
?>
<?php
    if($action ==='login'):
?>
    <div class="imgcontainer">
    <img src="1004916.png" alt="Avatar" class="avatar">
    </div>

    <div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
    </div>

  <div class="container" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
    <span class="psw"><a href="#">Signup</a></span>
  </div>

<?php
    endif;
?>
