<?php
function generateContent($page) {
    
    $ButtonWC = '<a href="places.phtml" class="btn btn-sm btn-outline-secondary" id="WC">View</a>';

     switch ($linkButton) {
        case '<a href="places.phtml" class="btn btn-sm btn-outline-secondary" id="WC">View</a>':
            $picture = ;
            $information = ;
            $link = ;
        
            echo "This is the Western Cape link.";
            break; 
        case '<a href="places.phtml" class="btn btn-sm btn-outline-secondary" id="EC">View</a>':
            
            echo "This is the Eastern Cape link.";
            break;
        
        default:
            
            break;
    }





    echo '
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        <div class="col">
          <div class="card shadow-sm">
            <div class="card-header">
              <img src="$image" class="bd-placeholder-img card-img-top" width="100%" height="225" alt="Your Image Description">
                </div>
              <div class="card-body" style="max-height: 250px; overflow-y: auto;">
                    <p class="card-text">
                    $information
                     <p>
                    <a href="$link" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Visit this place</a></p>
                    </div>
                       <!-- Rating Form -->
                      <div class="card-footer">
                      <form id="ratingForm" action="process.php" method="post">
                        <p>Rate this place:</p>
                        <label><input type="radio" name="rating" value="1"> ★</label>
                        <label><input type="radio" name="rating" value="2"> ★★</label>
                        <label><input type="radio" name="rating" value="3"> ★★★</label>
                        <label><input type="radio" name="rating" value="4"> ★★★★</label>
                        <label><input type="radio" name="rating" value="5"> ★★★★★</label>
                        <br><br>
                        <input type="hidden" id="comment" name="comment" value="">
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="btn-group">
                            <button type="button" onclick="showPopup()" class="btn btn-sm btn-outline-secondary">Rate</button>
                            <a href="reviews.html" class="btn btn-sm btn-outline-secondary" id="reviews">Reviews</a>
                          </div>
                          <small class="text-body-secondary"></small>
                        </div>
                      </form>
                  </div>
            </div>
        </div>

        </div>
    </div>
  </div>';




}
?>
