-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 05, 2024 at 09:59 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tourza`
--

-- --------------------------------------------------------

--
-- Table structure for table `images`
--

CREATE TABLE `images` (
  `imgID` int(11) NOT NULL,
  `imageName` varchar(225) NOT NULL,
  `image_dir` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `images`
--

INSERT INTO `images` (`imgID`, `imageName`, `image_dir`) VALUES
(1, 'aenp', 'web/aenp.jpg'),
(2, 'bb', 'web/bb.png'),
(3, 'bbwc', 'web/bbwc.jpg'),
(4, 'bfr', 'web/bfr.png'),
(5, 'bnr', 'web/bnr.jpg'),
(6, 'brits', 'web/brits.jpg'),
(7, 'cb', 'web/cb.jpg'),
(8, 'chhrp', 'web/chhrp.jpg'),
(9, 'd', 'web/d.jpg'),
(10, 'ds', 'web/ds.jpg'),
(11, 'el', 'web/el.jpg'),
(12, 'ep', 'web/ep.jpg'),
(13, 'frbopc', 'web/frbopc.jpg'),
(14, 'gr', 'web/gr.webp'),
(15, 'grctp', 'web/grctp.jpg'),
(16, 'gsk', 'web/gsk.jpg'),
(17, 'gsw', 'web/gsw.JPG'),
(18, 'h', 'web/h.jpg'),
(19, 'hbs', 'web/hbs.jpg'),
(20, 'hf', 'web/hf.jpg'),
(21, 'hip', 'web/hip.jpg'),
(22, 'hs', 'web/hs.jpg'),
(23, 'iwp', 'web/iwp.jpg'),
(24, 'jb', 'web/jb.jpg'),
(25, 'knbg', 'web/knbg.jpeg'),
(26, 'ksd', 'web/ksd.jpg'),
(27, 'm', 'web/m.jpg'),
(28, 'mb', 'web/mb.jpg'),
(29, 'mbk', 'web/mbk.jpg'),
(30, 'mbwc', 'web/mbwc.avif'),
(31, 'mc', 'web/mc.jpg'),
(32, 'mgrnw', 'web/mgrnw.jpg'),
(33, 'mhknw', 'web/mhknw.jpg'),
(34, 'mmgr', 'web/mmgr.jpg'),
(35, 'mnp', 'web/mnp.jpg'),
(36, 'mnpl', 'web/mnpl.jpg'),
(37, 'mnpnc', 'web/mnpnc.jpg'),
(38, 'ncc', 'web/ncc.jpg'),
(39, 'nh', 'web/nh.jpg'),
(40, 'nms', 'web/nms.jpg'),
(41, 'nql', 'web/nql.jpg'),
(42, 'p', 'web/p.jpg'),
(43, 'pa', 'web/pa.jpg'),
(44, 'pfs', 'web/pfs.jpg'),
(45, 'pl', 'web/pl.png'),
(46, 'plk', 'web/plk.jpg'),
(47, 'pnpnw', 'web/pnpnw.JPG'),
(48, 'prm', 'web/prm.jpg'),
(49, 'rnb', 'web/rnb.jpg'),
(50, 'rnnp', 'web/rnnp.jpg'),
(51, 'rnpncr', 'web/rnpncr.jpg'),
(52, 'salt', 'web/salt.jpg'),
(53, 'skk', 'web/skk.avif'),
(54, 'ssgr', 'web/ssgr.jpg'),
(55, 't', 'web/t.jpg'),
(56, 'tafnp', 'web/tafnp.webp'),
(57, 'tam', 'web/tam.webp'),
(58, 'tar', 'web/tar.jpg'),
(59, 'tbcv', 'web/tbcv.jpg'),
(60, 'tbh', 'web/tbh.jpg'),
(61, 'tcc', 'web/tcc.jpg'),
(62, 'tcogh', 'web/tcogh.webp'),
(63, 'tcohk', 'web/tcohk.jpg'),
(64, 'tcpnr', 'web/tcpnr.jpg'),
(65, 'tdbg', 'web/tdbg.jpg'),
(66, 'tfsnbg', 'web/tfsnbg.jpg'),
(67, 'tgd', 'web/tgd.jpg'),
(68, 'tgghnp', 'web/tgghnp.jpg'),
(69, 'tgnr', 'web/tgnr.jpg'),
(70, 'tgtosk', 'web/tgtosk.jpg'),
(71, 'thpm', 'web/thpm.jpg'),
(72, 'tibkm', 'web/tibkm.jpg'),
(73, 'tkep', 'web/tkep.jpg'),
(74, 'tkmm', 'web/tkmm.jpg'),
(75, 'tknpwc', 'web/tknpwc.jpg'),
(76, 'tktp', 'web/tktp.jpg'),
(77, 'tmms', 'web/tmms.jpg'),
(78, 'tmnpwc', 'web/tmnpwc.jpg'),
(79, 'tmp', 'web/tmp.jpeg'),
(80, 'tmznp', 'web/tmznp.jpg'),
(81, 'tnm', 'web/tnm.jpg'),
(82, 'tnmcs', 'web/tnmcs.jpg'),
(83, 'tpnr', 'web/tpnr.jpg'),
(84, 'trnrwc', 'web/trnrwc.jpg'),
(85, 'ttoacpt', 'web/ttoacpt.jpg'),
(86, 'ttoc', 'web/ttoc.jpg'),
(87, 'tvahwc', 'web/tvahwc.webp'),
(88, 'tvawft', 'web/tvawft.jpg'),
(89, 'tvd', 'web/tvd.jpg'),
(90, 'tvm', 'web/tvm.jpg'),
(91, 'twcaec', 'web/twcaec.jpg'),
(92, 'twlraa', 'web/twlraa.jpeg'),
(93, 'twsnbg', 'web/twsnbg.jpg'),
(94, 'tzn', 'web/tzn.avif'),
(95, 'umw', 'web/umw.JPG'),
(96, 'vybg', 'web/vybg.jpg'),
(97, 'wgr', 'web/wgr.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `place`
--

CREATE TABLE `place` (
  `placeID` varchar(10) NOT NULL,
  `placeName` varchar(255) NOT NULL,
  `placeDescription` varchar(6500) NOT NULL,
  `placeLink` varchar(3500) NOT NULL,
  `provinceID` varchar(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `place`
--

INSERT INTO `place` (`placeID`, `placeName`, `placeDescription`, `placeLink`, `provinceID`) VALUES
('aenp', 'addo elephant national park', 'Addo Elephant National Park, located in the Eastern Cape of South Africa, is a conservation success story and a haven for wildlife enthusiasts. Initially established to protect the last remaining elephants in the area, it has expanded to become a diverse sanctuary for various species, including the Big Five. Home to a significant elephant population, this park offers thrilling safari experiences, stunning landscapes, and the chance to witness these majestic creatures and other wildlife in their natural habitat.', 'https://www.addo.org.za/', 'EC'),
('bb', 'bela bela', 'Bela-Bela, formerly known as Warmbaths, is a popular resort town in Limpopo, South Africa, celebrated for its hot springs and relaxing spas. The town\'s name means \"boiling-boiling\" in Tswana, referencing the area\'s natural hot water springs renowned for their therapeutic properties. Visitors flock to Bela-Bela to unwind in the mineral-rich hot pools, indulge in spa treatments, and enjoy a variety of recreational activities. Beyond the hot springs, the town offers wildlife experiences, adventure sports, and a range of accommodation options, making it a favored destination for relaxation and rejuvenation in the heart of Limpopo.', 'http://www.foreverwarmbaths.co.za/', 'L'),
('bbwc', 'boulders beach', 'Boulders Beach, nestled along the picturesque Western Cape coastline in South Africa, is renowned for its unique charm as a home to a colony of African penguins. This sheltered beach with its granite boulders offers visitors a chance to observe these delightful birds up close in their natural habitat. Visitors can stroll along the wooden walkways that wind through the dunes and witness the penguins waddling along the shoreline or nesting in the surrounding vegetation. Besides penguin watching, Boulders Beach provides a serene setting for swimming and sunbathing, making it a popular destination for families and wildlife enthusiasts seeking a memorable seaside experience amidst a colony of charming African penguins.', 'https://www.capetown.travel/get-to-know-the-african-penguins-at-boulders-beach/', 'WC'),
('bfr', 'big five route', '<br>\r\n                      1. **Cheetah Route:** The Cheetah Route focuses on wildlife and conservation, highlighting attractions like the Cheetah Experience, where visitors can learn about and observe these magnificent animals up close. It also includes game reserves and wildlife sanctuaries that showcase a variety of indigenous species, providing an immersive wildlife experience.\r\n                      <br>\r\n                      2. **Lion Route:** This route centers around the majestic lion, offering opportunities to visit reserves and sanctuaries dedicated to lion conservation. Visitors can witness these incredible creatures in their natural habitat, learn about conservation efforts, and sometimes even participate in guided safaris or educational programs.\r\n                      <br>\r\n                      3. **Eagle Route:** The Eagle Route emphasizes birdwatching and showcases the diverse birdlife in the Free State. It includes birding hotspots, nature reserves, and parks where enthusiasts can spot various species of eagles, raptors, and other birds. This route appeals to birdwatchers and nature lovers keen on observing avian wildlife.\r\n                      <br>\r\n                      4. **Springbok Route:** Celebrating the region\'s natural beauty, the Springbok Route highlights the picturesque landscapes and outdoor activities available in the Free State. It features attractions such as nature reserves, hiking trails, and scenic spots where visitors can immerse themselves in the beauty of the area while engaging in activities like hiking, picnicking, and photography.\r\n                      <br>\r\n                      5. **Flamingo Route:** This route focuses on wetlands, lakes, and conservation areas where flamingos and other waterfowl thrive. Visitors can explore wetland habitats, go on birdwatching tours, and enjoy the serene beauty of these areas. It\'s a haven for those interested in aquatic ecosystems and birdlife.\r\n                      <br>\r\n                      Each route offers a distinct theme, catering to specific interests such as wildlife conservation, birdwatching, natural landscapes, and outdoor activities, providing a diverse range of experiences for visitors exploring the Free State.', 'https://www.destea.gov.za/?page_id=1028', 'FS'),
('bnr', 'balule nature reserve', 'Balule Nature Reserve, situated within the Greater Kruger National Park in Limpopo, South Africa, is a prime safari destination renowned for its raw wilderness and exceptional wildlife viewing. As part of the unfenced Greater Kruger ecosystem, Balule allows animals to roam freely across vast areas, offering visitors a chance to witness the Big Five and a multitude of other species in their natural habitat. The reserve provides various safari experiences, including game drives, walking safaris, and bush adventures, allowing guests to immerse themselves in the African bush while contributing to conservation efforts in this remarkable wildlife haven.', 'https://www.balule.org.za/', 'L'),
('brits', 'brits', 'Brits is a town located in the North West province of South Africa, known for its significant mining and agricultural activities. Originally a farming area, it expanded due to platinum mining developments in nearby regions. The town serves as a commercial and industrial center, with industries ranging from manufacturing to agriculture. Brits is surrounded by scenic landscapes and nature reserves, offering opportunities for outdoor activities like hiking and birdwatching. The Hartbeespoort Dam, a popular tourist destination, is in close proximity, attracting visitors with water sports and scenic views. The town maintains a balance between its industrial growth and preserving its natural surroundings, making it an appealing destination for both residents and tourists.', 'https://www.north-west-info.co.za/provinces/town/699/brits', 'NW'),
('cb', 'coffee bay', 'Coffee Bay, nestled on the Wild Coast of the Eastern Cape in South Africa, boasts stunning beaches, dramatic cliffs, and a relaxed vibe. It\'s a haven for beachgoers, surfers, and nature lovers. Visitors can explore the \"Hole in the Wall\" rock formation, enjoy activities like surfing and hiking, and immerse themselves in the vibrant local Xhosa culture. This off-the-beaten-path destination offers a unique blend of natural beauty and cultural experiences for a memorable coastal getaway.\r\n                      ', 'https://coffeebay.co.za/', 'EC'),
('chhrp', 'constitution hill human rights precinct', 'Constitution Hill Human Rights Precinct, located in Johannesburg, Gauteng, holds significant historical and symbolic value in South Africa\'s journey towards democracy and human rights. This site was formerly a prison complex where many political activists, including Nelson Mandela, were once held captive. Today, it stands as a living museum and heritage site, embodying the country\'s commitment to justice, reconciliation, and human rights.\r\n                      The precinct comprises various components, including the Old Fort, Women\'s Jail, Number Four, and the Constitutional Court. These spaces offer immersive exhibitions, guided tours, and multimedia experiences that depict the struggles against apartheid, the impact of segregation, and the country\'s path to democracy. Visitors encounter powerful narratives of resilience, activism, and the quest for equality.\r\n                      The Constitutional Court, established after South Africa\'s transition to democracy, symbolizes the nation\'s commitment to upholding human rights and the rule of law. This court, housed within the precinct, is renowned for its architectural significance and its role in safeguarding the country\'s constitution and principles of justice.\r\n                      Constitution Hill Human Rights Precinct serves as a living monument, fostering reflection, education, and dialogue about South Africa\'s past and the ongoing pursuit of equality and human rights for all.', 'https://www.constitutionhill.org.za/', 'G'),
('d', 'durban', 'Durban, located in KwaZulu-Natal, South Africa, is a vibrant coastal city famed for its golden beaches, warm Indian Ocean waters, and diverse cultural tapestry. Known as a melting pot of cultures, it\'s rich in heritage, showcasing influences from Zulu, Indian, and colonial histories. The city offers a dynamic mix of experiences, from its bustling markets and flavorful cuisine to iconic landmarks like the Moses Mabhida Stadium and uShaka Marine World. Durban\'s relaxed beachfront vibe, combined with its lively atmosphere and subtropical climate, makes it a compelling destination for tourists seeking sun, sea, and a blend of cultures.', 'https://visitdurban.travel/', 'KZN'),
('ds', 'dullstroom', 'Dullstroom, nestled in Mpumalanga, South Africa, is a charming town renowned for its picturesque landscapes, tranquil atmosphere, and outdoor pursuits. Situated amidst the highlands of the Drakensberg Mountains, it\'s a popular destination for nature lovers and outdoor enthusiasts. Known as the \"fly-fishing capital\" of South Africa, Dullstroom offers excellent trout fishing opportunities in its numerous dams and rivers. The town boasts a quaint and relaxed ambiance, with a variety of shops, galleries, and restaurants offering local crafts, cuisine, and outdoor gear. Visitors can explore the stunning scenery, enjoy birdwatching, hiking, and mountain biking in the surrounding area, or simply unwind in the serene surroundings. Dullstroom\'s blend of natural beauty, outdoor activities, and a laid-back vibe makes it an ideal getaway for those seeking a peaceful retreat in the heart of Mpumalanga\'s countryside.', 'https://dullstroom.co.za/', 'MP'),
('el', 'east london', 'East London, a coastal city in the Eastern Cape of South Africa, boasts beautiful beaches and a vibrant atmosphere. It serves as a pivotal economic center, featuring the country\'s sole river port. Combining urban convenience with seaside allure, East London offers cultural diversity, water activities, and a relaxed coastal lifestyle, attracting visitors and locals alike.', 'https://www.britannica.com/place/East-London', 'EC'),
('ep', 'emperors palace', 'Emperors Palace is a lavish resort and casino complex situated in Kempton Park, Gauteng, South Africa. Known for its opulent architecture and extensive entertainment options, the complex boasts a variety of hotels, a Las Vegas-style casino, convention centers, theaters, restaurants, and bars. It\'s a popular destination for both tourists and locals, offering a vibrant mix of entertainment, gaming, dining, and accommodation options. With its luxurious amenities and diverse entertainment offerings, Emperors Palace stands as a premier leisure destination in Gauteng, catering to a wide range of interests and tastes.', 'https://emperorspalace.com/', 'G'),
('frbopc', 'falcon ridge bird of prey centre', 'Falcon Ridge Bird of Prey Centre in KwaZulu-Natal, South Africa, is a haven for bird enthusiasts and nature lovers. Dedicated to raptor conservation, the center houses a diverse collection of birds of prey. Visitors can witness captivating flying displays and educational presentations showcasing the birds\' impressive skills and behaviors. Falcon Ridge offers an immersive experience, allowing guests to learn about these majestic creatures and their crucial role in the ecosystem while fostering an appreciation for these magnificent birds.', 'https://www.drakensbergexperience.com/listings/falcon-ridge-bird-of-prey-center/', 'KZN'),
('gr', 'graaff reinet', 'Graaff-Reinet, nestled in the Eastern Cape of South Africa, is a historic town known for its Cape Dutch architecture and rich cultural heritage. Set against the backdrop of the Camdeboo National Park, it boasts scenic landscapes, including the Valley of Desolation. With a blend of history, stunning vistas, and a vibrant community, Graaff-Reinet remains a captivating destination for travelers seeking a glimpse into South Africa\'s past and natural beauty.', 'https://www.graaffreinet.co.za/', 'EC'),
('grctp', 'gold reef city theme park', 'Gold Reef City Theme Park, nestled in Gauteng, South Africa, is a captivating blend of history, entertainment, and adrenaline-pumping rides. This theme park offers a unique experience by combining the excitement of exhilarating rides with the allure of a historical gold mining town. Visitors can immerse themselves in the rich heritage of Johannesburg\'s gold rush era while enjoying a wide array of thrilling attractions. From heart-racing roller coasters to interactive exhibits showcasing the city\'s mining history, Gold Reef City Theme Park caters to both adventure-seekers and history enthusiasts. It\'s a vibrant destination where the past meets present-day fun, providing a memorable and diverse experience for visitors of all ages.', 'https://www.goldreefcity.co.za/', 'G'),
('gsk', 'graskop', 'Graskop, situated in Mpumalanga, South Africa, is a quaint town renowned for its stunning scenery and proximity to natural wonders. Positioned on the edge of the Drakensberg escarpment, Graskop serves as a gateway to the famous Panorama Route, offering breathtaking views of the region\'s iconic landmarks. Visitors flock to Graskop to explore attractions like the awe-inspiring Blyde River Canyon, the majestic God\'s Window viewpoint, the intriguing Bourke\'s Luck Potholes, and the cascading Lisbon and Berlin Falls. The town itself exudes a relaxed charm, with a variety of shops, restaurants, and accommodations catering to travelers exploring the nearby natural wonders. Graskop\'s central location and its access to remarkable natural attractions make it a popular stopover for tourists seeking to immerse themselves in Mpumalanga\'s breathtaking landscapes and geological marvels.', 'https://www.graskop.co.za/', 'MP'),
('gsw', 'gods window', 'God\'s Window is a breathtaking viewpoint situated in Mpumalanga, South Africa, renowned for its awe-inspiring panoramic vistas. Perched on the Drakensberg escarpment, it offers sweeping views of the Lowveld region, with sights that stretch across lush forests, deep ravines, and the expansive landscapes below. Visitors are treated to an almost ethereal experience as they stand at the edge of the cliffs, feeling as if they\'re gazing out from the edge of the world. The scenery, often shrouded in mist and surrounded by rich biodiversity, creates a serene and mystical atmosphere. God\'s Window is a must-visit for nature enthusiasts, photographers, and anyone seeking to witness the sheer beauty of South Africa\'s natural landscapes.', 'https://www.graskop.co.za/seedo/', 'MP'),
('h', 'hogsback', 'Hogsback, nestled in the Eastern Cape\'s Amathole Mountains, is a mystical village known for its enchanting landscapes inspired by J.R.R. Tolkien. Surrounded by lush forests and waterfalls, it\'s a haven for nature lovers and hikers seeking serene beauty and tranquility. The village\'s magical ambiance invites visitors to explore hiking trails and immerse themselves in the mystical charm of this captivating mountain retreat.', 'https://visithogsback.co.za/site/', 'EC'),
('hbs', 'hartbeespoort', 'Hartbeespoort, located in the North West province of South Africa, is a picturesque town nestled around the Hartbeespoort Dam. Known for its stunning natural beauty, it\'s a popular weekend getaway spot for locals and tourists alike. The dam offers various water activities like boating, fishing, and water sports, while the surrounding Magaliesberg mountains provide opportunities for hiking, mountain biking, and exploring nature trails. The area is also home to wildlife sanctuaries, art galleries, craft markets, and restaurants offering diverse cuisines. With its scenic landscapes and diverse attractions, Hartbeespoort is a charming destination for relaxation and outdoor adventures.', 'https://www.hartbeespoortonline.co.za/', 'NW'),
('hf', 'howick falls', 'Howick Falls in KwaZulu-Natal, South Africa, is a breathtaking natural attraction known for its scenic beauty and cultural significance. Cascading from a height of around 95 meters (312 feet), the waterfall is a striking sight amidst lush surroundings. Besides its natural allure, Howick Falls holds cultural importance to the Zulu people, who believe it to be a sacred site. Visitors can admire the impressive waterfall, explore nearby viewpoints, and soak in the tranquility of this majestic natural wonder.', 'https://www.thesaunter.co.za/listing/howick-falls/', 'KZN'),
('hip', 'hluhluwe imfolozi park', 'Hluhluwe-iMfolozi Park, situated in KwaZulu-Natal, South Africa, is the oldest proclaimed nature reserve in Africa. Spanning 96,000 hectares, it\'s renowned for its conservation of endangered species like rhinos, as well as the Big Five. The park\'s diverse landscapes, from savannas to riverine forests, provide an ideal habitat for various wildlife. Hluhluwe-iMfolozi Park offers excellent safari experiences and stands as a pivotal site in conservation history.', 'http://www.hluhluwereservations.co.za/Hluhluwe_Umfolozi_Map.asp', 'KZN'),
('hs', 'hoedspruit', 'Hoedspruit, situated in the Limpopo province of South Africa, serves as a gateway to some of the country\'s most renowned wildlife reserves and natural wonders. Known for its proximity to Kruger National Park and private game reserves like Timbavati and Klaserie, Hoedspruit is a hub for wildlife enthusiasts and safari adventures. The town itself has a relaxed atmosphere with charming cafes, local craft shops, and galleries. Its strategic location near the Blyde River Canyon and the Drakensberg Mountains makes it an ideal base for exploring the region\'s diverse landscapes and enjoying memorable safari experiences.', 'https://www.hoedspruit.co.za/', 'L'),
('iwp', 'isimangaliso wetland park', 'Isimangaliso Wetland Park in KwaZulu-Natal, South Africa, is a UNESCO World Heritage Site known for its diverse ecosystems. Spanning 332,000 hectares, it boasts lakes, coastal dunes, savannas, and wetlands. The park teems with wildlife like hippos, rhinos, and varied bird species. Its cultural significance, with evidence of ancient human habitation, adds to its allure. Isimangaliso showcases successful conservation efforts, balancing preservation with sustainable tourism and supporting local communities.', 'https://isimangaliso.com/index.php/visitors/isimangaliso-tags.html', 'KZN'),
('jb', 'jeffreys bay', '  Jeffreys Bay, nestled along the Eastern Cape coast of South Africa, is a world-renowned surfing paradise. This coastal town is famous for its perfect waves, attracting surfers from across the globe. Beyond surfing, it offers a laid-back atmosphere, stunning beaches, and a welcoming community, making it a haven for beach lovers and adventurers alike.', 'https://www.jeffreysbaytourism.org/', 'EC'),
('knbg', 'kirstenbosch national botanical garden', 'Kirstenbosch National Botanical Garden, nestled at the foot of Table Mountain in Cape Town, Western Cape, is a stunning haven for biodiversity and natural beauty. Renowned for its diverse flora, it showcases South Africa\'s indigenous plant species across various themed gardens and landscapes. The garden offers visitors a chance to explore tranquil pathways, marvel at unique plant collections, and appreciate the breathtaking scenery. It\'s not just a botanical paradise but also a hub for conservation, research, and education, making it a must-visit destination for nature enthusiasts and botany lovers.', 'https://www.capetown.travel/relax-on-the-lawns-of-cape-towns-prettiest-garden/', 'WC'),
('ksd', 'klerksdorp', 'Klerksdorp, situated in the North West province of South Africa, is a vibrant city with a rich mining history. Initially established around the 19th-century gold rush, it has evolved into a thriving commercial and industrial center. The city\'s economy revolves around mining, agriculture, and manufacturing, contributing significantly to the region\'s prosperity. Klerksdorp hosts various cultural and recreational attractions, including the Klerksdorp Museum, showcasing the area\'s geological and historical heritage, and the Faan Meintjies Nature Reserve, providing opportunities for outdoor activities and wildlife viewing. The city\'s growth is evident through its modern infrastructure, educational institutions, and healthcare facilities, making Klerksdorp a dynamic urban center in the North West province.', 'https://www.sa-venues.com/attractionsnwp/klerksdorp.php', 'NW'),
('m', 'makhanda', 'Makhanda, formerly known as Grahamstown, is a culturally rich town in the Eastern Cape of South Africa. Renowned for its annual National Arts Festival, it\'s a hub for arts, culture, and academia. The town is steeped in history, boasting elegant Victorian architecture and several educational institutions. With its vibrant arts scene, historical significance, and academic prominence, Makhanda remains a dynamic cultural center in the Eastern Cape.', 'https://www.grahamstown-info.co.za/town', 'EC'),
('mb', 'mbombela', 'Mbombela, previously known as Nelspruit, serves as the capital of Mpumalanga province in South Africa. It\'s a vibrant city nestled in the heart of the region, renowned for its accessibility to nearby natural attractions like the Kruger National Park, Sudwala Caves, and the scenic Panorama Route. As a central hub, Mbombela boasts modern amenities, shopping centers, and a diverse culinary scene. The city\'s strategic location makes it a popular gateway for tourists exploring Mpumalanga\'s natural wonders, and its lively atmosphere reflects a blend of urban convenience with the stunning natural beauty that characterizes the province. Mbombela also hosts cultural events, markets, and showcases the rich heritage of the region, making it a dynamic and inviting destination for travelers.', 'https://www.southafrica.net/gl/en/travel/category/places-to-go/big-city-life/mbombela class=', 'MP'),
('mbk', 'magoebaskloof', 'Magoebaskloof, nestled in the picturesque mountainous region of Limpopo, South Africa, is renowned for its breathtaking scenery, lush forests, and serene landscapes. Named after the Magoebaskloof Pass that winds through the area, this region offers a cool climate and stunning vistas. Visitors flock to Magoebaskloof for its natural beauty, including indigenous forests, waterfalls like the Debengeni Falls, and outdoor activities such as hiking, birdwatching, and mountain biking. The area also boasts charming villages, farm stalls, and opportunities to experience the tranquility and natural splendor of Limpopo\'s highlands.', 'https://magoebasklooftourism.co.za/', 'L'),
('mbwc', 'maclears beacon ', 'Maclear\'s Beacon stands as a significant landmark atop Table Mountain in the Western Cape of South Africa. Named after Sir Thomas Maclear, the astronomer who erected it in the 19th century, it\'s the highest point on Table Mountain, offering panoramic views of Cape Town and its surroundings. Serving as a trigonometrical beacon for surveying purposes in the past, it now marks a popular hiking destination. Hikers frequently trek to this point, relishing the challenging yet rewarding trails that culminate in breathtaking vistas from the summit. Maclear\'s Beacon not only boasts historical significance but also provides an unforgettable vantage point for those seeking awe-inspiring views of the Western Cape\'s scenic landscapes.', 'https://hiketablemountain.co.za/what-is-the-highest-point-on-table-mountain/', 'WC'),
('mc', 'monte casino', 'Montecasino, situated in Gauteng, South Africa, is a premier entertainment destination renowned for its unique Italian-inspired architecture and a diverse range of attractions. This complex offers a multifaceted experience, blending entertainment, dining, shopping, and leisure activities in one vibrant location. Visitors can explore an array of entertainment options, including a world-class casino, theaters hosting live shows and musicals, and a selection of bars and nightclubs for nightlife enthusiasts. The complex also features an array of restaurants offering various cuisines, alongside cafes and boutique shops. Its meticulously designed architecture transports guests to a picturesque Italian village, creating a charming ambiance for leisurely strolls and vibrant social experiences. Montecasino stands as a bustling hub, inviting locals and tourists alike to indulge in a rich tapestry of entertainment and leisure opportunities within Gauteng.', 'https://www.montecasino.co.za/', 'G'),
('mgrnw', 'madikwe game reserve', 'Madikwe Game Reserve, situated in the North West province of South Africa, is a premier safari destination renowned for its diverse wildlife and conservation efforts. Established in the 1990s, this reserve spans over 75,000 hectares of pristine bushveld and offers the Big Five safari experience, including lions, elephants, rhinos, leopards, and buffaloes. It\'s one of South Africa\'s largest game reserves and is malaria-free, making it a family-friendly destination. The reserve focuses on sustainable tourism, supporting local communities and wildlife conservation initiatives. Visitors can enjoy thrilling game drives, guided walks, and luxurious accommodations in lodges that blend harmoniously with the natural landscape. Madikwe stands as a testament to successful conservation practices while providing an unforgettable safari experience in a breathtaking wilderness setting.', 'https://madikwesafarilodge.co.za/', 'NW'),
('mhknw', 'mahikeng', 'Mahikeng, the capital city of the North West province in South Africa, holds historical significance as it was the site of significant events during the country\'s past. Also known as Mafikeng, it played a role in the Anglo-Boer War, where the town\'s siege lasted for several months and became a symbol of resistance. The city has a mix of cultural influences, reflecting its diverse population. Mahikeng hosts attractions like the Mafikeng Museum, showcasing the town\'s history and the Mafikeng Game Reserve, offering glimpses of wildlife. It\'s also a center for education and government administration in the province, contributing to its importance beyond its historical legacy. Today, Mahikeng continues to evolve, blending its historical past with modern developments, serving as a cultural, administrative, and educational hub in the North West province.', 'https://en.wikivoyage.org/wiki/Mahikeng', 'NW'),
('mmgr', 'mala mala game reserve', 'MalaMala Game Reserve stands as one of Africa\'s iconic and exclusive safari destinations, situated within the Sabi Sand Game Reserve in Mpumalanga, South Africa. Renowned for its unrivaled wildlife experiences, MalaMala is celebrated for its vast wilderness, exceptional game viewing, and luxurious accommodations. As one of the oldest and most prestigious private game reserves, it offers prime opportunities to witness the Big Five and an abundance of other wildlife species in their natural habitat. Visitors can enjoy guided game drives and bushwalks led by expert rangers and trackers, ensuring memorable and intimate encounters with Africa\'s iconic animals. The reserve\'s commitment to conservation, coupled with its top-notch facilities and extraordinary wildlife sightings, positions MalaMala as a premier safari destination, providing guests with an unforgettable immersion into the wild heart of Africa.', 'https://malamala.com/', 'MP'),
('mnp', 'marakele national park', 'Marakele National Park, nestled in the heart of the Waterberg Mountains in Limpopo, South Africa, is a scenic and biodiverse wildlife sanctuary. The park boasts a stunning landscape of mountains, valleys, and grasslands, providing a habitat for a wide array of species, including the iconic Big Five. Visitors can explore diverse ecosystems, from open savannas to dense forests, and enjoy game drives, hiking trails, and birdwatching. Marakele is renowned for its unique landscapes, rich biodiversity, and conservation efforts, offering an immersive safari experience in a beautiful and less crowded setting.', 'https://marakelenationalpark.co.za/', 'L'),
('mnpl', 'mapungubwe national park', 'Mapungubwe National Park, located in Limpopo, South Africa, is a UNESCO World Heritage Site famed for its rich cultural history and breathtaking landscapes. The park encompasses the remains of the ancient Mapungubwe Kingdom, showcasing archaeological sites, artifacts, and evidence of early African civilizations dating back to the Iron Age. The park\'s diverse ecosystems, including savannahs, riverine forests, and sandstone formations, provide a habitat for a variety of wildlife, including elephants, leopards, and various bird species. Visitors can explore the park through guided tours, hiking trails, and game drives, experiencing a blend of natural beauty and historical significance in this captivating African landscape.', 'https://mapungubwenationalpark.co.za/', 'L'),
('mnpnc', 'mokala national park', 'Mokala National Park, nestled in the Northern Cape of South Africa, is a gem renowned for its diverse landscapes and rich\r\n                      biodiversity. Spanning approximately 26,485 hectares, the park showcases a blend of Kalahari thornveld, savanna, and rocky\r\n                      hills, creating a haven for various wildlife species. Visitors can witness an array of animals, including endangered species \r\n                      like the black rhinoceros and roan antelope, alongside herds of giraffes, zebras, and numerous bird species. Mokala offers\r\n                      opportunities for game drives, guided walks, and birdwatching, inviting guests to immerse themselves in the tranquility of this lesser-known but captivating wilderness.', 'https://mokalanationalpark.co.za/', 'NC'),
('nh', 'naval hill', 'Naval Hill in the Free State, nestled in Bloemfontein, boasts not only breathtaking views and a wildlife reserve but also hosts the Naval Hill Planetarium. This state-of-the-art facility offers visitors an immersive journey through space and time, with captivating astronomical shows and educational programs. The planetarium is a hub for astronomy enthusiasts, students, and families eager to explore the wonders of the universe. Alongside the Franklin Game Reserve and the iconic Nelson Mandela statue, the Naval Hill Planetarium enriches the hill\'s offerings, providing an educational and awe-inspiring experience for those intrigued by the cosmos. It stands as a unique blend of natural beauty, wildlife, historical significance, and celestial exploration, making Naval Hill a multifaceted attraction in the heart of Bloemfontein.', 'http://denc.ncpg.gov.za/index.php/component/sppagebuilder/?view=page&id=6&Itemid=40', 'FS'),
('nms', 'neslon mandela square', 'Nelson Mandela Square, situated in Sandton, Johannesburg, stands as a vibrant and iconic public space honoring the legacy of the revered South African leader, Nelson Mandela. Central to the square is a towering bronze statue of Nelson Mandela, a symbol of his enduring impact and contribution to the nation\'s history.\r\n                      Surrounded by upscale shopping malls, restaurants, cafes, and luxury boutiques, the square serves as a bustling social hub and a popular gathering place for locals and tourists alike. The statue of Mandela, with his arm outstretched, embodies his vision of unity and reconciliation.\r\n                      The square\'s lively atmosphere, coupled with its striking architecture and amenities, makes it a favored destination for leisure, shopping, dining, and entertainment. It stands not only as a tribute to Mandela but also as a symbol of South Africa\'s progress, resilience, and the values he championed throughout his life.\r\n                    ', 'https://nelsonmandelasquare.co.za/', 'G'),
('nql', 'namaqualand', 'Namaqualand, situated in the Northern Cape of South Africa, is a unique and striking region known for its breathtaking landscapes and annual floral spectacle. This semi-desert area transforms into a colorful tapestry during the spring months (usually August to September), when the wildflowers bloom in a magnificent display of vibrant hues across the otherwise arid terrain. The Namaqualand region encompasses diverse landscapes, including rocky outcrops, sandy plains, and rugged mountains, creating a habitat for a variety of wildlife adapted to the harsh conditions. Beyond the floral spectacle, the area offers opportunities for outdoor activities like hiking, birdwatching, and exploring the rugged beauty of this arid yet enchanting landscape.', 'https://namakwatoere.com/', 'NC'),
('p', 'pretoria', 'Pretoria, often referred to as the Jacaranda City due to its streets lined with jacaranda trees, is the administrative capital of South Africa, situated in the Gauteng province. It\'s a city characterized by a blend of historic architecture, government buildings, and natural beauty. Home to the Union Buildings, where the country\'s government offices are located, Pretoria boasts a rich history evident in landmarks like the Voortrekker Monument and the Kruger House Museum. Beyond its administrative significance, Pretoria offers botanical gardens, museums, vibrant markets, and cultural attractions that draw visitors keen on exploring its diverse heritage and experiencing its unique charm. With its mix of historical significance, government institutions, and cultural attractions, Pretoria stands as a multifaceted city with much to offer residents and tourists alike.', 'https://pretoria.co.za/', 'G'),
('pa', 'port alfred', 'Port Alfred, nestled along the Sunshine Coast of the Eastern Cape in South Africa, is a charming town known for its scenic beauty, relaxed atmosphere, and a wealth of outdoor activities. This coastal gem boasts stunning beaches that cater to both leisure seekers and water sports enthusiasts. The Kowie River adds to its allure, offering opportunities for boating, fishing, and river cruises. History buffs can explore the town\'s rich heritage through its historical buildings, such as the iconic Wharf Street, while nature lovers can revel in the beauty of nearby game reserves and nature trails. The Royal Port Alfred Golf Club presents a picturesque setting for golf aficionados. The town\'s laid-back vibe, coupled with its natural splendor, makes it an ideal destination for those seeking a peaceful retreat amidst breathtaking landscapes and a touch of South African coastal charm.', 'https://portalfred.co.za/', 'EC'),
('pfs', 'potchefstroom', 'Potchefstroom, located in the North West province of South Africa, is a historic town with a vibrant atmosphere. It\'s renowned for its educational institutions, including the North-West University, which attracts students from across the country. The town has a rich cultural heritage and is often referred to as the \"City of Expertise,\" emphasizing its academic and cultural significance. Potchefstroom hosts various events and festivals, such as the Aardklop Arts Festival, celebrating arts, music, and culture. Additionally, it has a strong agricultural presence, with farming and agribusiness playing a vital role in its economy. The town offers a blend of historical landmarks, modern amenities, and a lively student community, making Potchefstroom a dynamic and diverse hub within the North West province.', 'https://www.sa-venues.com/attractionsnwp/potchefstroom.php', 'NW'),
('pl', 'phalaborwa', 'Phalaborwa, located in Limpopo, South Africa, is a town renowned for its proximity to the Kruger National Park and its mining industry. Known as the \"Town of Two Summers\" due to its year-round warm weather, Phalaborwa serves as a gateway to one of Africa\'s most famous wildlife reserves. The town\'s primary economic activities revolve around mining, particularly for minerals like copper and phosphates. Tourists often use Phalaborwa as a base for exploring Kruger Park, enjoying safari adventures, and experiencing the natural beauty and wildlife of the region.', 'https://phalaborwa.co.za/', 'L'),
('plk', 'polokwane', 'Polokwane, the capital city of Limpopo province in South Africa, is a vibrant urban center with a mix of modern amenities and historical significance. Formerly known as Pietersburg, it\'s a hub for commerce, government, and culture in the region. The city offers a blend of urban conveniences, shopping malls, and a lively nightlife scene while also retaining its cultural heritage through sites like the Polokwane Game Reserve and the Bakone Malapa Northern Sotho Open-Air Museum, showcasing traditional local life. Polokwane serves as a gateway to the natural wonders of Limpopo, making it a convenient stop for travelers exploring the province\'s diverse landscapes and wildlife.', 'https://www.southafrica.net/gl/en/travel/category/places-to-go/big-city-life/polokwane', 'L'),
('pnpnw', 'pilanesberg national park', 'Pilanesberg National Park, nestled in South Africa\'s North West province, is a wildlife haven spread across an ancient volcanic crater. It\'s renowned for its rich biodiversity, including the iconic Big Five and diverse landscapes like grasslands and wooded valleys. Visitors can embark on guided or self-driven safaris, encountering a wealth of wildlife against a backdrop of stunning scenery. The park\'s unique geological formation and malaria-free environment make it a popular destination for experiencing the African bush.', 'https://www.pilanesbergnationalpark.org/?gclid=CjwKCAiA-vOsBhAAEiwAIWR0TaA6KNwE6eFm5Vr15iahNZlbyN395K6OMc9t85S777p8HDmLYaVgzxoCsbEQAvD_BwE', 'NW'),
('prm', 'pilgrims rest', 'Pilgrim\'s Rest, situated in Mpumalanga, South Africa, is a historic town steeped in gold rush lore and rich heritage. Designated as a National Monument and a living museum, Pilgrim\'s Rest preserves its 19th-century gold mining past, offering visitors a glimpse into the bygone era of prospectors and pioneers. The town\'s charming streets are lined with well-preserved historic buildings, including original miners\' cottages, museums, and artifacts that showcase the gold rush history and the lifestyle of the early settlers. Visitors can explore museums, take guided tours, and even try their hand at gold panning, experiencing firsthand the allure and hardships of the gold rush days. The picturesque setting amidst lush landscapes adds to the town\'s allure, making Pilgrim\'s Rest a captivating destination that blends history, nostalgia, and natural beauty for visitors interested in South Africa\'s fascinating past.', 'https://www.pilgrimsrest.org.za/', 'MP'),
('rnb', 'rustenburg', 'Rustenburg, located in the North West province of South Africa, is a bustling city known for its mining industry, particularly platinum mining, which significantly contributes to the region\'s economy. The city has seen rapid development, offering a mix of urban amenities and natural attractions. It\'s close to the scenic Magaliesberg Mountains, providing opportunities for outdoor activities like hiking, mountain biking, and exploring the picturesque landscapes. Rustenburg is also home to cultural sites such as the Kgaswane Mountain Reserve and the Rustenburg Museum, showcasing the area\'s history and heritage. With a thriving commercial sector, diverse population, and proximity to natural wonders, Rustenburg serves as an essential economic and cultural hub in the North West province.', 'https://www.britannica.com/place/Rustenburg', 'NW'),
('rnnp', 'royal natal national park', 'Royal Natal National Park, situated in KwaZulu-Natal, South Africa, is a scenic and pristine wilderness area renowned for its majestic Drakensberg Mountains. Home to the iconic Amphitheatre, a towering rock wall, the park offers stunning hiking trails, including the popular Tugela Gorge and Chain Ladders route. Visitors can explore diverse landscapes, from grassy plains to dramatic cliffs and waterfalls like the Tugela Falls, one of the world\'s highest waterfalls. This UNESCO World Heritage Site is a haven for outdoor enthusiasts, offering breathtaking vistas and opportunities to immerse oneself in the natural beauty of the Drakensberg region.', 'https://royalnatal.info/', 'KZN'),
('rnpncr', 'richtersveld national park', 'Richtersveld National Park, situated in the Northern Cape of South Africa, is a rugged and captivating wilderness known for its unique desert landscapes and cultural significance. This arid region, characterized by dramatic mountains, deep gorges, and the flow of the Orange River, is a UNESCO World Heritage Site. The park is home to a variety of succulent plants, including the iconic halfmens, as well as a diverse array of desert-adapted wildlife. What sets Richtersveld apart is its association with the Nama people, who have lived in harmony with this challenging environment for centuries. Visitors can immerse themselves in the Nama culture, explore the stark beauty of the landscape through hiking trails and 4x4 routes, and experience the tranquility and raw allure of this remote and pristine wilderness.', 'https://www.richtersveldnationalpark.co.za/', 'NC'),
('salt', 'the southern african large telescope', 'The Southern African Large Telescope (SALT) is a cutting-edge astronomical observatory situated in the Northern Cape \r\n                      province of South Africa. It\'s one of the largest single optical telescopes in the southern hemisphere, boasting a primary\r\n                      mirror measuring 11 meters in diameter. Positioned at the South African Astronomical Observatory near the town of Sutherland,\r\n                      SALT enables astronomers to explore the cosmos with remarkable precision, studying distant galaxies, stars, and celestial phenomena. \r\n                      Its location in an area known for clear skies and minimal light pollution enhances its capabilities, allowing for groundbreaking research and discoveries in the field of astronomy.', 'https://www.salt.ac.za/', 'NC'),
('skk', 'skukuza', 'Skukuza, located in Mpumalanga, South Africa, is a pivotal hub and the largest rest camp within the iconic Kruger National Park. Serving as the park\'s administrative center, Skukuza offers visitors a range of facilities, accommodations, and activities. It\'s strategically positioned along the Sabie River, providing picturesque views and exceptional wildlife sightings right from the camp. The camp features various lodging options, from campsites to comfortable bungalows, making it a popular base for exploring the park\'s diverse ecosystems and abundant wildlife. Visitors can enjoy game drives, guided walks, birdwatching, and educational programs to experience the park\'s rich biodiversity up close. Skukuza also houses a museum and research facilities, providing insights into the park\'s conservation efforts and its natural history. As a central point in Kruger National Park, Skukuza offers an ideal blend of convenience, wildlife experiences, and comfort for visitors exploring one of Africa\'s most renowned wildlife reserves.', 'https://www.krugerpark.co.za/Kruger_National_Park_Lodging_&_Camping_Guide-travel/skukuza-camp.html', 'MP'),
('ssgr', 'sabi sand game reserve', 'Sabi Sand Game Reserve, located in Mpumalanga, South Africa, is renowned for its exceptional wildlife and luxurious safari experiences. As part of the Greater Kruger National Park ecosystem, Sabi Sand offers exclusive, high-end safari lodges and camps nestled in an area teeming with diverse wildlife. Visitors have the opportunity to encounter the renowned Big Five (lion, leopard, elephant, buffalo, and rhinoceros) along with an abundance of other species, all within a pristine natural environment. The reserve\'s private concessions allow for intimate and immersive game drives and guided walks, providing guests with unforgettable encounters with Africa\'s magnificent wildlife. The combination of stunning landscapes, remarkable biodiversity, and top-notch accommodations makes Sabi Sand Nature Reserve a sought-after destination for safari enthusiasts and nature lovers worldwide.', 'https://sabisand.co.za/', 'MP'),
('t', 'thabazimbi', 'Thabazimbi, located in Limpopo, South Africa, is a mining town known for its rich iron ore deposits. The name \"Thabazimbi\" translates to \"Mountain of Iron\" in the Tswana language, a reference to the prominent iron ore mountain in the area. The mining industry has been a significant economic driver for the town, attracting workers and businesses to the region. Thabazimbi also offers proximity to natural attractions like the Marakele National Park, providing opportunities for wildlife encounters and outdoor activities amidst the beautiful landscapes of Limpopo.', 'https://www.waterberg-information.co.za/region/town/675', 'L'),
('tafnp', 'the augrabies falls national park', 'The Augrabies Falls National Park, located in the Northern Cape of South Africa, is a captivating natural reserve renowned for\r\n                      its spectacular waterfall on the Orange River. The park spans approximately 820 square kilometers and is characterized by its rugged\r\n                      landscapes, rocky outcrops, and the impressive Augrabies Falls. The falls cascade down a granite gorge, plunging about 56 meters into\r\n                      a tumultuous pool below. Beyond the falls, the park boasts diverse flora and fauna, with unique desert-adapted plants and various wildlife\r\n                      species such as dassies, monkeys, and a variety of birdlife. Visitors can explore the park through hiking trails, viewpoints, and guided tours, immersing themselves in the raw beauty of this arid yet mesmerizing landscape.', 'https://augrabiesnationalpark.co.za/', 'NC'),
('tam', 'the apartheid museum', 'The Apartheid Museum, situated in Johannesburg, Gauteng, serves as a poignant and immersive tribute to South Africa\'s tumultuous apartheid era. This museum stands as a powerful testament to the country\'s history, portraying the stark realities and impact of apartheid, the system of institutionalized racial segregation and oppression that persisted for decades. Through interactive exhibits, multimedia displays, artifacts, and personal accounts, the museum offers a comprehensive and emotionally stirring journey. Visitors gain profound insights into the struggles, injustices, and resilience of South Africans during this era, highlighting both the horrors of apartheid and the nation\'s journey towards reconciliation and democracy. The museum\'s thought-provoking displays aim to educate and provoke reflection, fostering a deeper understanding of the past and its influence on South Africa\'s present and future. It stands as a vital institution preserving the memory of apartheid while promoting dialogue, understanding, and the pursuit of a more inclusive society.', 'https://www.apartheidmuseum.org/', 'G'),
('tar', 'the ash river', 'The Ash River, near Clarens in the Free State, South Africa, is renowned for its spectacular white-water rafting experiences. Flowing through the picturesque landscapes of the Maluti Mountains, the river offers thrilling rapids and stunning scenery, attracting adventure seekers and nature enthusiasts alike. Its rapids range from gentle ripples to adrenaline-pumping challenges, making it a popular destination for both beginners and experienced rafters. The Ash River provides an exhilarating outdoor adventure against the backdrop of breathtaking natural beauty, offering an unforgettable experience for visitors exploring the Free State region.', 'https://www.clarens.co.za/listing/white-water-river-rafting-on-the-ash-river/', 'FS'),
('tbcv', 'the basotho cultural village', 'The Basotho Cultural Village in the Free State is a living museum that beautifully preserves and showcases the rich cultural heritage of the Basotho people. Set against the backdrop of the scenic Golden Gate Highlands, this village offers visitors a glimpse into traditional Basotho life, architecture, crafts, and customs. The village features authentically reconstructed huts and buildings representing different historical periods, providing insight into the lifestyle, traditions, and craftsmanship of the Basotho community. Visitors can engage with local artisans demonstrating traditional crafts like pottery, weaving, and beadwork, and they can participate in cultural activities such as music, dance, and storytelling. The Basotho Cultural Village serves as an immersive and educational experience, allowing visitors to appreciate and learn about the vibrant culture and heritage of the Basotho people within the picturesque landscapes of the Free State.', 'https://www.sanparks.org/parks/golden-gate-highlands/what-to-do/activities/basotho-cultural-village', 'FS'),
('tbh', 'the big hole', 'The Big Hole, also known as the Kimberley Mine, is a massive crater in Kimberley, Northern Cape, South Africa. It\'s\r\n                       an iconic site, once a bustling diamond mine and now a historic landmark. This immense crater was excavated by hand \r\n                       over a period of years during the diamond rush in the late 19th century. The hole spans approximately 1,097 meters in\r\n                      circumference and reaches a depth of about 240 meters, exposing layers of earth and rock that tell the story of diamond \r\n                      mining in the region. Today, it serves as a museum and tourist attraction, offering visitors a glimpse into the fascinating history of diamond mining in South Africa.', 'https://thebighole.co.za/', 'NC');
INSERT INTO `place` (`placeID`, `placeName`, `placeDescription`, `placeLink`, `provinceID`) VALUES
('tcc', 'the cango caves', 'The Cango Caves, situated in the Western Cape of South Africa, stand as an awe-inspiring natural wonder. These extensive underground caverns boast a labyrinth of chambers adorned with spectacular limestone formations, such as stalactites and stalagmites, formed over millions of years. Visitors can embark on guided tours through different sections of the caves, experiencing the grandeur of the colossal halls and narrow passageways. The Cango Caves offer a captivating glimpse into the intricate beauty and geological history of these ancient underground formations, making it a captivating destination for explorers and nature enthusiasts alike.', 'https://www.cango-caves.co.za/', 'WC'),
('tcogh', 'the cape of good hope', 'The Cape of Good Hope, situated at the southern tip of the Cape Peninsula in Western Cape, South Africa, is a legendary and iconic landmark. Revered for its stunning natural beauty and rich maritime history, this rugged headland offers breathtaking vistas of dramatic cliffs, pristine beaches, and diverse flora and fauna. Visitors can explore the Cape Point Nature Reserve, home to a variety of wildlife, hike along scenic trails, and witness the meeting of the Atlantic and Indian Oceans. The Cape of Good Hope holds historical significance as a navigational point and continues to captivate travelers with its sheer beauty and untamed coastal landscapes, making it a must-visit destination for those exploring the Western Cape.', 'https://capepoint.co.za/', 'WC'),
('tcohk', 'the cradle of humankind', 'The Cradle of Humankind in Gauteng, South Africa, is a UNESCO World Heritage Site known for its rich archaeological significance. This area is home to caves and fossil deposits containing ancient hominid fossils, offering profound insights into human evolution. Visitors can explore museums, guided tours, and exhibits that showcase these discoveries, providing a captivating journey through our evolutionary past. It stands as a testament to humanity\'s origins, offering a unique opportunity to learn about our shared ancestry and the story of human evolution.', 'https://www.maropeng.co.za/content/page/maropeng-visitor-centre', 'G'),
('tcpnr', 'the cape point nature reserve', 'The Cape Point Nature Reserve, located at the southern tip of the Cape Peninsula in the Western Cape of South Africa, is a breathtakingly diverse wilderness area that showcases stunning landscapes, rich biodiversity, and dramatic coastal scenery. Renowned for its rugged cliffs, fynbos-covered hills, and pristine beaches, this reserve offers visitors an array of activities such as hiking, wildlife viewing, and picnicking amidst its natural splendor. The iconic Cape Point, within the reserve, marks the meeting point of the Atlantic and Indian Oceans and boasts panoramic views from its historic lighthouse. Explorers can encounter a variety of wildlife, including ostriches and baboons, while traversing the scenic trails. The Cape Point Nature Reserve stands as a captivating destination for nature enthusiasts and adventurers seeking to immerse themselves in the raw beauty of the Western Cape\'s coastal landscapes.', 'https://capepoint.co.za/visitus/', 'WC'),
('tdbg', 'the durban botanic gardens', 'The Durban Botanic Gardens in KwaZulu-Natal, South Africa, is Africa\'s oldest surviving botanical garden. Spanning 37 hectares, it\'s a lush haven showcasing an extensive collection of indigenous and exotic plants. The gardens offer serene landscapes, educational programs, and a rich history, making it a delightful spot for relaxation and exploration.', 'https://durbanbotanicgardens.org.za/', 'KZN'),
('tfsnbg', 'the free state national botanical garden', 'The Free State National Botanical Garden, situated in Bloemfontein, is a haven of indigenous plants and biodiversity. Spanning across acres of diverse landscapes, it showcases the rich flora of the Free State region and South Africa. Visitors can explore a variety of themed gardens, each highlighting different plant species, ecosystems, and horticultural displays. The garden serves as an educational and recreational hub, offering guided tours, walking trails, and educational programs to learn about the region\'s plant life and conservation efforts. Its serene ambiance provides a tranquil escape for nature enthusiasts, photographers, and families seeking to immerse themselves in the beauty of indigenous flora within the Free State.', 'https://www.sanbi.org/gardens/free-state/', 'FS'),
('tgd', 'the gariep dam', 'The Gariep Dam in the Free State is an impressive feat of engineering, standing as the largest dam in South Africa and a pivotal water reservoir for the region. Spanning the Orange River, this massive dam not only serves as a crucial water source for agriculture, industry, and communities but also offers a picturesque setting for recreational activities. The dam\'s vast expanse creates opportunities for water-based adventures like fishing, boating, and water sports, attracting outdoor enthusiasts and vacationers. Surrounding the dam, visitors can find resorts, lodges, and camping sites that capitalize on the scenic beauty of the area, providing a serene retreat amidst the Free State\'s natural landscapes. The Gariep Dam embodies both practical importance as a water resource and serves as a popular destination for leisure, offering a blend of natural beauty and recreational opportunities in South Africa\'s Free State.', 'https://gariepdam.com/nature/', 'FS'),
('tgghnp', 'the golden gate highlands national park', 'The Golden Gate Highlands National Park in the Free State is a breathtaking natural wonder characterized by its golden-hued sandstone cliffs, rugged rock formations, and expansive grasslands. This park is renowned for its scenic beauty and diverse wildlife, offering visitors a captivating outdoor experience. Nestled amidst the Maluti Mountains, the park provides a range of activities, including hiking trails that wind through stunning landscapes, revealing panoramic vistas at every turn. It\'s home to an array of wildlife, such as eland, zebras, and numerous bird species, making it a haven for nature enthusiasts and photographers. The park\'s distinctive golden sandstone formations, contrasting with the lush greenery, create a visual spectacle, making Golden Gate Highlands a cherished destination for those seeking natural beauty and outdoor adventures in the heart of South Africa\'s Free State.', 'https://www.sanparks.org/parks/golden-gate-highlands', 'FS'),
('tgnr', 'the geogap nature reserve', 'The Goegap Nature Reserve, nestled in the Northern Cape of South Africa, is a captivating expanse of arid landscapes\r\n                      and unique flora. Spanning over 15,000 hectares, this reserve showcases the rugged beauty of the Namaqualand region, \r\n                      known for its stunning displays of wildflowers during the spring bloom. Visitors can explore the diverse terrain,\r\n                       which includes rocky outcrops, plains, and valleys, hosting a variety of wildlife such as antelope, mongoose, and \r\n                       tortoises. The reserve also boasts a rich diversity of succulents, including quiver trees and various species of \r\n                       flowering plants, making it a haven for nature enthusiasts, hikers, and photographers eager to witness the striking beauty of this semi-desert environment.', 'http://denc.ncpg.gov.za/index.php/component/sppagebuilder/?view=page&id=6&Itemid=40', 'NC'),
('tgtosk', 'the gateway theatre of shopping', 'The Gateway Theatre of Shopping in KwaZulu-Natal, South Africa, stands as one of Africa\'s largest shopping and entertainment complexes. Boasting a vast array of stores, restaurants, and entertainment options, it offers a diverse shopping experience. From high-end fashion brands to local artisans, visitors can explore a wide range of offerings. Additionally, the mall features a variety of entertainment facilities such as cinemas, an arcade, a climbing wall, and a wave pool, ensuring a lively and diverse experience for shoppers and entertainment seekers alike.', 'https://gatewayworld.co.za/', 'KZN'),
('thpm', 'the hector pieterson memorial', 'The Hector Pieterson Memorial, located in Soweto, Gauteng, commemorates the 1976 Soweto Uprising, a pivotal moment in South Africa\'s struggle against apartheid. The memorial is named after Hector Pieterson, a 13-year-old boy who was one of the first casualties of the uprising. It consists of a museum and a memorial designed to honor Hector and the hundreds of students who protested against the apartheid government\'s language policy, demanding better education. The memorial serves as a powerful reminder of the youth\'s bravery and the sacrifices made during the fight for freedom in South Africa.', 'https://www.sahistory.org.za/place/hector-pieterson-memorial-and-museum-soweto', 'G'),
('tibkm', 'the iziko bo kaap museum', 'The Iziko Bo-Kaap Museum in the Western Cape of South Africa is a cultural gem nestled in the vibrant Bo-Kaap neighborhood of Cape Town. Housed in a beautifully preserved historic home, the museum showcases the rich heritage and traditions of the Cape Malay community. Visitors can explore exhibitions that delve into the area\'s history, from its origins as a vibrant multicultural hub to the stories of the community\'s resilience and cultural practices. The museum offers insights into the distinct architecture, cuisine, music, and religious practices that shape the unique identity of the Bo-Kaap. It stands as a testament to the area\'s diverse and colorful history, offering an immersive experience into Cape Town\'s multicultural fabric.', 'https://www.iziko.org.za/museums/bo-kaap-museum/', 'WC'),
('tkep', 'the knysna elephant park', 'The Knysna Elephant Park, located in the Western Cape of South Africa, is a sanctuary dedicated to the conservation and protection of African elephants. Renowned for its ethical approach to elephant interactions, the park offers visitors a unique and up-close experience with rescued and rehabilitated elephants in a natural and spacious environment. Guests can engage in guided tours, learn about elephant behavior and conservation efforts, and even have the opportunity to interact with these majestic animals through guided feeding and touching experiences. The Knysna Elephant Park provides an educational and ethical encounter with elephants, making it a remarkable destination for wildlife enthusiasts seeking a deeper understanding and appreciation for these incredible creatures.', 'https://knysnaelephantpark.co.za/', 'WC'),
('tkmm', 'the kimberley mine museum', 'The Kimberley Mine Museum, situated in the Northern Cape of South Africa, stands as a captivating testament to the diamond mining history in the region. It\'s an immersive museum located on the site of the famous Kimberley Mine, also known as the Big Hole. The museum offers a glimpse into the area\'s diamond rush era of the late 19th century. Visitors can explore historic buildings, exhibitions, and displays showcasing the tools, equipment, and the mining methods used during that time. The highlight of the museum is the Big Hole itself, a massive crater excavated by hand during the diamond rush, providing a tangible link to the area\'s rich mining heritage and offering visitors a unique and educational experience.', 'https://thebighole.co.za/', 'NC'),
('tknpwc', 'the karoo national park', 'The Karoo National Park in the Western Cape of South Africa is a vast wilderness characterized by semi-arid landscapes and diverse habitats. This protected area offers a glimpse of the Karoo\'s stark beauty, with rugged mountains and unique wildlife like antelope, zebra, and rhinoceros. Visitors can explore via self-drives, guided tours, or hiking trails to witness the park\'s stunning scenery and discover the remarkable adaptations of flora and fauna to the arid environment. The park provides a serene and immersive experience, showcasing the natural wonders of the Karoo within the Western Cape.', 'https://www.karoo-southafrica.com/koup/karoo-national-park/', 'WC'),
('tktp', 'the kgalagadi transfrontier park', 'The Kgalagadi Transfrontier Park is a sprawling conservation area situated in the northern parts of South Africa and \r\n                      Botswana. It spans over 3.6 million hectares, making it one of the largest wilderness areas in the world. This park is\r\n                      renowned for its breathtaking semi-arid landscapes, characterized by red sand dunes, sparse vegetation, and an abundance \r\n                      of wildlife, particularly the iconic Kalahari desert-adapted species like lions, cheetahs, gemsbok, and springbok. Visitors\r\n                       can experience the park\'s untamed beauty through game drives, guided tours, and self-drive safaris, reveling in the serenity of this remote and captivating wilderness.', 'https://kgalagaditransfrontierpark.co.za/', 'NC'),
('tmms', 'the moses mabhida stadium', 'The Moses Mabhida Stadium, situated in Durban, KwaZulu-Natal, is an architectural marvel and a prominent sports and entertainment venue. Built for the 2010 FIFA World Cup, it boasts a striking design with its iconic arch, offering panoramic views of the city. Beyond sports events, the stadium hosts concerts, adventure activities like the SkyCar, and guided tours, serving as a multifaceted symbol of Durban\'s vibrancy and modernity.', 'https://www.mmstadium.com/', 'KZN'),
('tmnpwc', 'table mountain national park', 'Table Mountain National Park in the Western Cape of South Africa is a vast protected area known for its diverse landscapes, including the iconic Table Mountain. Offering panoramic views, hiking trails, and rich biodiversity, the park encompasses mountains, valleys, and coastal stretches. Visitors can explore Cape Town\'s famous landmark, Table Mountain, and discover stunning coastal scenery, wildlife, and historic landmarks across the Cape Peninsula. With activities like hiking, wildlife viewing, and enjoying breathtaking vistas, the park is a cherished destination for nature lovers and adventurers alike.', 'https://tablemountainnationalpark.org/', 'WC'),
('tmp', 'the maboneng precinct', 'The Maboneng Precinct in Johannesburg, Gauteng, is a vibrant and dynamic neighborhood that has undergone a remarkable transformation. Initially an industrial area, it\'s now a trendy hub for arts, culture, and creativity. The precinct is filled with art galleries, boutiques, restaurants, cafes, and studios, showcasing the work of local artists and entrepreneurs. It\'s a melting pot of diverse cultures, attracting both locals and tourists seeking a unique and eclectic experience. Maboneng hosts various events, markets, and festivals, contributing to its lively atmosphere and making it a must-visit destination for those interested in exploring Johannesburg\'s thriving arts and cultural scene.', 'https://mabonengprecinct.com/', 'G'),
('tmznp', 'the mountain zebra national park', 'The Mountain Zebra National Park, situated in the Eastern Cape of South Africa, is a haven for wildlife enthusiasts and nature lovers. This conservation area is renowned for its successful efforts in preserving the endangered Cape mountain zebra, offering visitors a chance to witness these majestic creatures in their natural habitat. The park\'s diverse landscape, characterized by rolling hills, expansive plains, and rugged mountains, provides a habitat for various other wildlife species, including buffalo, cheetahs, various antelope species, and a variety of birdlife. Visitors can explore the park through guided game drives, walking trails, or self-drive routes, immersing themselves in the scenic beauty while encountering a wide array of indigenous flora and fauna. With its conservation efforts, striking landscapes, and opportunities for wildlife sightings, the Mountain Zebra National Park stands as a testament to South Africa\'s commitment to preserving its natural heritage.\r\n                      ', 'https://mountainzebranationalpark.co.za/', 'EC'),
('tnm', 'the national museum', 'The National Museum in the Free State, located in Bloemfontein, stands as a cultural and scientific treasure trove, offering diverse exhibits that showcase the region\'s natural and cultural heritage. It houses extensive collections covering archaeology, paleontology, ethnology, and natural history. Visitors can explore exhibits featuring fossils, artifacts, and interactive displays that detail South Africa\'s rich history, from ancient civilizations to the natural wonders of the region. The museum also houses a significant collection of art, showcasing the diverse cultural expressions of the Free State. With its educational programs, engaging exhibitions, and a commitment to preserving and promoting the area\'s heritage, the National Museum serves as a captivating destination for locals and tourists interested in the cultural and scientific tapestry of South Africa.', 'https://nasmus.co.za/', 'FS'),
('tnmcs', 'the nelson mandela capture site', 'The Nelson Mandela Capture Site in KwaZulu-Natal, South Africa, marks the spot where Nelson Mandela, the iconic anti-apartheid leader, was captured in 1962. The site features a sculpture installation that, when viewed from a specific angle, forms Mandela\'s face, symbolizing his journey and legacy. It\'s a significant historical landmark commemorating Mandela\'s pivotal moment and his fight against apartheid, inviting reflection on South Africa\'s history and the pursuit of justice and equality.', 'https://www.thecapturesite.co.za/', 'KZN'),
('tpnr', 'timbavati private nature reserve', 'Timbavati Private Nature Reserve, located in Mpumalanga, South Africa, is a pristine and renowned wildlife sanctuary forming part of the Greater Kruger National Park. Famous for its untamed beauty and exceptional biodiversity, Timbavati offers visitors an exclusive safari experience in a vast and unspoiled wilderness. The reserve is celebrated for its Big Five sightings, including lion, leopard, elephant, buffalo, and rhinoceros, along with a wealth of other wildlife species. Timbavati is distinguished by its open landscapes, diverse ecosystems, and commitment to conservation efforts. Visitors can embark on guided game drives, bushwalks, and night safaris led by experienced guides, providing intimate and immersive encounters with Africa\'s magnificent wildlife. The reserve also boasts luxurious lodges and camps that offer guests a blend of comfort and a genuine safari experience, making Timbavati a sought-after destination for nature enthusiasts and safari adventurers alike.', 'https://timbavati.co.za/', 'MP'),
('trnrwc', 'the robberg nature reserve', 'The Robberg Nature Reserve, nestled along the Garden Route in the Western Cape of South Africa, is a pristine coastal reserve renowned for its dramatic landscapes and abundant biodiversity. This protected area encompasses a rugged peninsula offering scenic hiking trails that wind through diverse habitats, including fynbos-covered hills, rocky cliffs, and sandy beaches. Visitors can embark on exhilarating hikes offering panoramic views of the Indian Ocean, encountering unique flora and fauna along the way. The reserve is home to diverse wildlife, including seals, dolphins, and various bird species. Robberg Nature Reserve captivates nature enthusiasts and adventurers seeking an immersive experience amidst stunning coastal scenery and natural beauty along South Africa\'s picturesque Garden Route.', 'https://www.capenature.co.za/reserves/robberg-nature-reserve', 'WC'),
('ttoacpt', 'the two oceans aquarium', 'The Two Oceans Aquarium in Cape Town, Western Cape, stands as an awe-inspiring showcase of marine life from the Atlantic and Indian Oceans, a testament to the region\'s incredible biodiversity. Home to a diverse array of aquatic species, the aquarium offers immersive exhibits where visitors can witness everything from colorful tropical fish to mesmerizing sharks and rays. Educational programs and interactive displays highlight conservation efforts and the importance of preserving marine ecosystems. The Two Oceans Aquarium provides an engaging and educational experience for visitors of all ages, allowing them to explore the wonders of both the Atlantic and Indian Oceans without leaving the captivating city of Cape Town.', 'https://www.aquarium.co.za/', 'WC'),
('ttoc', 'the tropic of capricorn', 'The Tropic of Capricorn crosses through the Limpopo province of South Africa, marking the southernmost latitude where the sun can appear directly overhead at noon. This imaginary line, situated at approximately 23.5 degrees south of the equator, holds geographical significance and is a point of interest for travelers. In Limpopo, visitors can often find markers or signs denoting the Tropic of Capricorn, offering an opportunity for tourists to capture a unique geographical landmark and appreciate its significance as it relates to Earth\'s axial tilt and the sun\'s positioning during the year.', 'https://www.geocaching.com/geocache/GC231YC', 'L'),
('tvahwc', 'the victoria and alfred hotel', 'The Victoria & Alfred Hotel in Cape Town, Western Cape, stands as an iconic and luxurious waterfront destination. Located in the prestigious V&A Waterfront, it offers guests a blend of historic charm and modern comfort. Housed in a beautifully restored historic building, the hotel provides elegant accommodations with views of the harbor or Table Mountain. Its central location allows easy access to a myriad of attractions, shopping, dining, and entertainment options within the vibrant Waterfront precinct. Known for its exceptional service, sophisticated ambiance, and attention to detail, the Victoria & Alfred Hotel is a sought-after choice for travelers seeking a refined and indulgent experience in Cape Town.', 'https://www.waterfront.co.za/accomm/victoria-and-alfred-hotel/', 'WC'),
('tvawft', 'the v and a waterfront', 'The V&A Waterfront, situated in Cape Town, Western Cape, stands as a vibrant hub blending history, culture, shopping, entertainment, and stunning waterfront views. This iconic destination offers a diverse array of experiences, from world-class shopping in its malls and markets to delectable dining options overlooking the harbor. Visitors can explore historical landmarks like the Clock Tower and the Chavonnes Battery Museum or embark on boat tours to Robben Island. The V&A Waterfront also hosts live music, art exhibitions, and cultural events, creating a lively atmosphere for both locals and tourists. With its blend of attractions and breathtaking views of Table Mountain, it remains a must-visit spot for those seeking a dynamic and enriching experience in the Western Cape.', 'https://www.waterfront.co.za/', 'WC'),
('tvd', 'the vredefort dome', 'The Vredefort Dome in the Free State, South Africa, is a UNESCO World Heritage Site recognized for its immense scientific significance and stunning natural beauty. It represents the world\'s largest and oldest meteorite impact structure, formed over two billion years ago when a massive asteroid struck Earth. The impact left a distinctive geological feature, creating a dome-shaped crater that spans approximately 300 kilometers in diameter. Visitors to the Vredefort Dome can explore its unique landscapes, including rivers, hills, and diverse flora and fauna. It serves as a testament to the planet\'s geological history and offers opportunities for outdoor activities such as hiking, birdwatching, and scenic exploration. This remarkable site stands as a testament to the Earth\'s ancient history, captivating both scientists and nature enthusiasts alike.', 'https://www.vredefortdome.co.za/', 'FS'),
('tvm', 'the voortrekker', 'The Voortrekker Monument, located in Gauteng, South Africa, stands as a significant symbol of Afrikaner history and heritage. This imposing monument commemorates the pioneer spirit and struggles of the Voortrekkers, early Dutch settlers who migrated inland during the 19th century. Towering atop a hill, the monument\'s design reflects both historical and cultural significance, with its distinct architecture and symbolic elements. Visitors can explore its museum, which houses exhibits detailing the Voortrekkers\' journey, their battles, and the formation of Afrikaner identity. The monument\'s serene surroundings offer panoramic views of Pretoria and its landscapes, inviting contemplation and reflection on South Africa\'s historical narratives. As a testament to a pivotal period in the country\'s history, the Voortrekker Monument stands as a revered landmark, preserving the legacy and cultural heritage of the Voortrekkers for generations to come.', 'https://www.sahistory.org.za/place/voortrekker-monument', 'G'),
('twcaec', 'the windmill casino and entertainment centre', 'The Windmill Casino and Entertainment Centre in the Free State is a vibrant hub offering a blend of gaming excitement, entertainment, dining, and accommodation. Situated in Bloemfontein, South Africa, this destination boasts a lively casino floor with a wide array of slot machines and table games, catering to gaming enthusiasts. Additionally, it features various dining options ranging from casual to fine dining, ensuring visitors can indulge in diverse culinary experiences. The center also offers live entertainment, including concerts, shows, and events, providing guests with an all-encompassing entertainment experience. Moreover, its hotel accommodations provide a comfortable stay for those looking to extend their visit. With its diverse offerings, the Windmill Casino and Entertainment Centre stands as a prominent attraction in the Free State region, catering to a wide range of interests for visitors seeking leisure and excitement.', 'https://www.suninternational.com/windmill/?gad_source=1&gclid=CjwKCAiApuCrBhAuEiwA8VJ6JsvHgYCEwZ95xTBA8jKdrU-TpGsaZTULa9ZVLAmMLBr1QArZfLHOmRoCSgsQAvD_BwE', 'FS'),
('twlraa', 'tenikwa wildlife rehabilitation and awereness centre', 'Tenikwa Wildlife Rehabilitation and Awareness Centre in the Western Cape is a conservation facility focused on rehabilitating indigenous wildlife, especially big cats like cheetahs and leopards. Through guided tours and educational experiences, it aims to raise awareness about wildlife conservation and the threats facing these species. Visitors can engage responsibly with the animals while learning about rehabilitation efforts and the importance of protecting South Africa\'s wildlife. Tenikwa serves as a valuable resource for wildlife enthusiasts, promoting environmental stewardship and conservation in the Western Cape.', 'https://tenikwa.com/', 'WC'),
('twsnbg', 'the walter sisulu national botanical garden', 'The Walter Sisulu National Botanical Garden, nestled in Gauteng, South Africa, is a scenic haven showcasing the natural beauty and biodiversity of the region. Named after Walter Sisulu, a prominent anti-apartheid activist, this expansive botanical garden offers a serene escape from the city bustle. Visitors are greeted by lush landscapes, tranquil waterfalls, and indigenous flora, creating a picturesque setting for relaxation and exploration. The garden\'s diverse plant collections, including rare and endangered species, provide an educational experience for nature enthusiasts and botany lovers. Its well-maintained trails invite leisurely walks or hikes, leading to viewpoints offering breathtaking vistas of the surrounding landscape. The Walter Sisulu National Botanical Garden stands as a sanctuary for biodiversity, offering both peaceful retreats and opportunities for learning about South Africa\'s rich plant life and conservation efforts.', 'https://www.sanbi.org/gardens/walter-sisulu/', 'G'),
('tzn', 'tzaneen', 'Tzaneen, nestled in the lush greenery of Limpopo, South Africa, is a charming town surrounded by subtropical landscapes and fruit orchards. Renowned for its agricultural prowess, particularly in citrus farming, Tzaneen offers a picturesque setting with rolling hills, waterfalls, and fertile valleys. The town serves as a gateway to various natural attractions like the Tzaneen Dam, Debengeni Falls, and the Modjadji Cycad Reserve, home to the famous Modjadji Rain Queen\'s cycads. With its mild climate and scenic beauty, Tzaneen is a haven for nature lovers, offering outdoor activities, cultural experiences, and a tranquil escape into the heart of Limpopo\'s natural wonders.', 'https://www.limpopo-info.co.za/provinces/town/662/tzaneen', 'L'),
('umb', 'umhlanga main beach', ' Umhlanga Main Beach in KwaZulu-Natal, South Africa, is a popular and picturesque coastal destination known for its golden sands and clear waters. This Blue Flag beach offers a relaxed atmosphere, ideal for sunbathing, swimming, and family outings. With a vibrant promenade lined with shops, restaurants, and hotels, Umhlanga Main Beach provides both a scenic seaside experience and various amenities for visitors to enjoy a leisurely day by the ocean.', 'https://umhlangaaccommodation.co.za/things-to-do/', 'KZN'),
('umw', 'ushaka marine world', 'uShaka Marine World, located in Durban, KwaZulu-Natal, South Africa, is a vibrant marine theme park that combines entertainment, education, and conservation. Spanning over 16 hectares, it features a world-class aquarium with diverse marine life, including sharks, dolphins, and colorful fish. The park offers various attractions such as water slides, pools, a beach, and live shows, providing visitors with an exciting and immersive experience centered around marine conservation and aquatic entertainment.', 'https://ushakamarine.com/', 'KZN'),
('vybg', 'vryburg', 'Vryburg is a town situated in the North West province of South Africa. It serves as the agricultural and industrial hub of the region. With a rich history dating back to the late 1800s, Vryburg was established as a trading center and grew around a railway junction. The town boasts various historical sites like the Huhudi Community Hall and the Leon Taljaard Nature Reserve, offering opportunities for cultural exploration and outdoor activities. Agriculture plays a significant role in the town\'s economy, particularly in livestock farming and crop cultivation. Vryburg hosts events such as the Vryburg Show, showcasing agricultural excellence and local culture, making it a vibrant and dynamic town in the North West province.', 'https://www.vryburg-info.co.za/town/info', 'NW'),
('wgr', 'welgevonden game reserve', 'Welgevonden Game Reserve, located in Limpopo, South Africa, is a pristine wilderness area renowned for its remarkable biodiversity and conservation efforts. Spanning over 37,000 hectares, it\'s a Big Five reserve with diverse landscapes, including open grasslands, rugged mountains, and savannahs. Welgevonden offers exclusive safari experiences in a malaria-free environment, allowing visitors to explore the reserve\'s natural beauty and encounter a wide variety of wildlife, including elephants, lions, rhinos, leopards, and an array of bird species. With luxurious lodges and a focus on sustainable tourism, Welgevonden provides an immersive safari adventure while contributing to the preservation of South Africa\'s wildlife heritage.', 'https://www.welgevondengamereserve.org/specials?gclid=CjwKCAiA-vOsBhAAEiwAIWR0TZf_SbMet1qwldsooQoUPmdk5pglhwnRfXn12jn763-XOcpkad3ElxoCLKsQAvD_BwE', 'L');

-- --------------------------------------------------------

--
-- Table structure for table `rating`
--

CREATE TABLE `rating` (
  `ratingID` int(11) NOT NULL,
  `ratingValue` int(5) NOT NULL,
  `rateComment` varchar(500) NOT NULL,
  `placeID` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `images`
--
ALTER TABLE `images`
  ADD PRIMARY KEY (`imgID`);

--
-- Indexes for table `place`
--
ALTER TABLE `place`
  ADD PRIMARY KEY (`placeID`);

--
-- Indexes for table `rating`
--
ALTER TABLE `rating`
  ADD PRIMARY KEY (`ratingID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `images`
--
ALTER TABLE `images`
  MODIFY `imgID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=98;

--
-- AUTO_INCREMENT for table `rating`
--
ALTER TABLE `rating`
  MODIFY `ratingID` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
