<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box}

/* Set height of body and the document to 100% */
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial;
}

/* Style tab links */
.tablink {
  background-color: #555;
  color: white;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  font-size: 17px;
  width: 25%;
}

.tablink:hover {
  background-color: #777;
}

/* Style the tab content (and add height:100% for full page content) */
.tabcontent {
  color: white;
  display: none;
  padding: 100px 20px;
  height: 100%;
}

#Home {background-color: lightgrey;}
#lg {background-color: lightgrey;}
#sa {background-color: lightgrey;}
#uk {background-color: lightgrey;}
</style>
</head>
<body>

<button class="tablink" onclick="openPage('Home', this, 'orange')" id="defaultOpen">Home</button>
<button class="tablink" onclick="openPage('lg', this, 'orange')">LGBTQIA+</button>
<button class="tablink" onclick="openPage('sa', this, 'orange')">South Africa</button>
<button class="tablink" onclick="openPage('uk', this, 'orange')">United Kingdom</button>

<div id="Home" class="tabcontent">
  <h3 style = "font-size:60px; font-family:verdana;">Flags</h3>
  <p>A flag is a piece of fabric with a distinctive design and colours. It is used as a symbol, a signalling device, or for decoration.It is also used to refer to the graphic design employed, and flags have evolved into a general tool for rudimentary signalling and identification, especially in environments where communication is challenging (such as the maritime environment, where semaphore is used).</p>

</div>

<div id="lg" class="tabcontent">
  <h2>LGBTQIA+</h2>
  <img src="lgbtq_flag.jpg" alt="lgbtq flag" width="400" height="300">
  <p>LGBT is an initialism that stands for "lesbian, gay, bisexual, and transgender". In use since the 1990s, the initialism, as well as some of its common variants, functions as an umbrella tern for certain sexualities and gender identities. It may refer to anyone who is non-heterosexual or non-cisgender, instead of exclusively to people who are lesbian, gay, bisexual, or transgender. To recognize this inclusion, a popular variant, LGBTQ, adds the letter Q for those who identify as queer or are questioning their sexual or gender identity. The initialisms LGBT or GLBT are not agreed by everyone that they are supposed to include.</p>
  <span style="color:red;">We not straight.</span>
  <span style="color:yellow;">We not straight.</span>
  <span style="color:green;">We not straight.</span>
  <span style="color:blue;">We not straight.</span>
  <span style="color:purple;">We not straight.</span>
</div>

<div id="sa" class="tabcontent">
  <h2>South Africa</h2>
  <img src="southafrican_flag.jpg" alt="south african flag" width="400" height="300">
  <p>SA is the southernmost country in Africa. It is bounded to the south 2,798 kilometres (1,739 mi) of coastline that stretches along the South Atlanticand Indian Oceans; to the north by the neighbouring countries of Namibia,Botswana, and Zimbabwe; and to the east and the northeast by Mozambique and Eswatini. It also completely enclaves the country Lesotho. It is a biodiversity hotspot, with unique biomes, plant and animal life. With over 60 million people, the country is the world's 24th-most populous nation and covers an area of 1,221,037 square kilometres(471,445 square miles).</p>
  <span style="color:red;">We rich in minerals.</span>
  <span style="color:white;">We rich in minerals.</span>
  <span style="color:green;">We rich in minerals</span>
  <span style="color:blue;">We rich in minerals</span>
  <span style="color:yellow;">We rich in minerals</span>
  <span style="color:black;">We rich in minerals</span>
</div>

<div id="uk" class="tabcontent">
  <h2>United Kingdom</h2>
  <img src="uk_flag.jpg" alt="UK flag" width="400" height="300">
  <p>UK is a country in Northwestern Europe,off the northwestern coast of the continental mainland. It comprises England, Scotland, Wales and Northen Ireland. It is surrounded by the Atlantic Ocean, the North Sea, the English Channel, the Celtic Sea and the Irish Sea. The total area of the UK is 242,495 square kilometres (93,628 sq mi), with an estimated 2023 population of over 68 million people.</p>
  <span style="color:red;">We very royal.</span>
  <span style="color:blue;">We very royal.</span>
  <span style="color:white;">We very royal.</span>
</div>

<script>
function openPage(pageName,elmnt,color) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].style.backgroundColor = "";
  }
  document.getElementById(pageName).style.display = "block";
  elmnt.style.backgroundColor = color;
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>
   
</body>
</html> 