<!DOCTYPE html> <!-- represents the type of the document in hmtl5-->
<html>
<body> <!-- everything that will be visible comes in the body-->

<h1>paragraphs in different colors</h1> <!--h1-h6 are headings--> 
<p>These colored paragraphs represents flags</p> <!--these are paragraphs-->

<h3>LGBTQI+ flag</h3> 
<p style="color:red;">We not straight.</p>
<p style="color:yellow;">We not straight.</p>
<p style="color:green;">We not straight.</p>
<p style="color:blue;">We not straight.</p>
<p style="color:purple;">We not straight.</p>
<br>
<h3>South African flag</h3> 
<p style="color:red;">We rich in minerals.</p>
<p style="color:white;">We rich in minerals.</p>
<p style="color:green;">We rich in minerals</p>
<p style="color:blue;">We rich in minerals</p>
<p style="color:yellow;">We rich in minerals</p>
<p style="color:black;">We rich in minerals</p>
<br>


<!-- <a tags are used for hyperlinks and href is an attribute-->
<a href="https://www.github.com">This is a link for Github</a> 

<!-- <img tag used to add an image you can include attributes if you like-->
<!-- all extra things you wanna add for your project like graphics should be in the same folder-->
<!--<img src="1004916" alt="pink panda" width="104" height="142">-->

</body>
</html>