<!DOCTYPE html> <!-- represents the type of the document in hmtl5-->
<html>
<body> <!-- everything that will be visible comes in the body-->

<h1>My First Heading</h1> <!--h1-h6 are headings--> 
<p>My first paragraph.</p> <!--these are paragraphs-->

<h2>My second Heading</h2> 
<p>My second paragraph.</p>

<h3>My third Heading</h3> 
<p>My third paragraph.</p>

<h4>My Fourth Heading</h4>  
<p>My Fourth paragraph.</p>

<h5>My Fifth Heading</h5> 
<p>My Fifth paragraph.</p>

<h6>My sixth Heading</h6> 
<p>My sixth paragraph.</p>

<!-- <a tags are used for links and href is an attribuute-->
<a href="https://www.github.com">This is a link for Github</a> 

<!-- <img tag used to add an image you can include attributes if you like-->
<!-- all extra things you wanna add for your project like graphics should be in the same folder-->
<img src="" alt="" width="104" height="142">

</body>
</html>