<!DOCTYPE html> <!-- represents the type of the document in hmtl5-->
<html>
<body> <!-- everything that will be visible comes in the body-->

<h1 style="font-size:60px;">Learn about flags</h1> <!--h1-h6 are headings--> 
<p>These colored paragraphs represents flags</p> <!--these are paragraphs-->

<h2>LGBTQIA+ flag</h2> 
<p>LGBT is an initialism that stands for "lesbian, gay, bisexual, and transgender". In use since the 1990s, the initialism, as well as some of its common variants, functions as an umbrella tern for certain sexualities and gender identities. It may refer to anyone who is non-heterosexual or non-cisgender, instead of exclusively to people who are lesbian, gay, bisexual, or transgender. To recognize this inclusion, a popular variant, LGBTQ, adds the letter Q for those who identify as queer or are questioning their sexual or gender identity. The initialisms LGBT or GLBT are not agreed by everyone that they are supposed to include.</p>
<p style="color:red;">We not straight.</p>
<p style="color:yellow;">We not straight.</p>
<p style="color:green;">We not straight.</p>
<p style="color:blue;">We not straight.</p>
<p style="color:purple;">We not straight.</p>
<br>
<h2>South African flag</h2> 
<p>SA is the southernmost country in Africa. It is bounded to the south 2,798 kilometres (1,739 mi) of coastline that stretches along the South Atlanticand Indian Oceans; to the north by the neighbouring countries of Namibia,Botswana, and Zimbabwe; and to the east and the northeast by Mozambique and Eswatini. It also completely enclaves the country Lesotho. It is a biodiversity hotspot, with unique biomes, plant and animal life. With over 60 million people, the country is the world's 24th-most populous nation and covers an area of 1,221,037 square kilometres(471,445 square miles).</p>
<p style="color:red;">We rich in minerals.</p>
<p style="color:white;">We rich in minerals.</p>
<p style="color:green;">We rich in minerals</p>
<p style="color:blue;">We rich in minerals</p>
<p style="color:yellow;">We rich in minerals</p>
<p style="color:black;">We rich in minerals</p>
<br>
<h2>United Kingdom flag</h2>
<p>UK is a country in Northwestern Europe,off the northwestern coast of the continental mainland. It comprises England, Scotland, Wales and Northen Ireland. It is surrounded by the Atlantic Ocean, the North Sea, the English Channel, the Celtic Sea and the Irish Sea. The total area of the UK is 242,495 square kilometres (93,628 sq mi), with an estimated 2023 population of over 68 million people.</p>
<p style="color:red;">We very royal.</p>
<p style="color:blue;">We very royal.</p>
<p style="color:white;">We very royal.</p>

</body>
</html>