<!--<html>
 <head> 
 <title>home Page</title>
 </head>   
 <body>
 <style> body {background-color: #c4a484;} </style>
 <form action="viewclient.php"  method="post">
    Enter your name: <input type="text" name="name"></br>
    Enter your surname: <input type="text" name="surname"></br>
    Enter your email address: <input type="text" name="email"></br>
    Enter your cellphone number: <input type="text" name="cellno"></br>
    <input type="submit">    
 </form>
 </body>
</html>-->


